config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: %i[index show destroy] do
    get :show_archived
    get :search
  end

  resources :lists do
    resources :list_users
    resources :tasks
    resources :tasks do
      put :finish
    end
  end
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  TAG_LIST = %w[travail école course lecture sport remboursement sortie recette voyage famille].freeze

  validates :tag, inclusion: { in: TAG_LIST, message: 'must be from list' }
  validates :listname, length: { maximum: 30, message: 'must be shorter than 30 chars' }
  validates :description, length: { maximum: 100, message: 'must be shorter than 100 chars' }

  has_many :list_users
  has_many :users, through: :list_users

  has_many :tasks

  def archived
    if tasks.count == 0 || (tasks.map{|t| t.finished}.include?false)
      return false
    else
      return true
    end
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :get_current_user
  before_action :set_list, only: %i[show edit update destroy]
  # before_action :test_owner

  def index
    @lists = @user.lists
  end

  def show; end

  def new
    respond_to do |format|
      @list = List.new
      format.js {}
    end
  end

  def create
    respond_to do |format|
      @list = List.create(list_params)
      ListUser.create(list: @list, user: @user)
      format.js {}
    end
  end

  def edit
    respond_to do |format|
      format.js {}
    end
  end

  def update
    respond_to do |format|
      @list.update(list_params)
      format.js {}
    end
  end

  def destroy
    respond_to do |format|
      @list.destroy
      format.js {}
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.permit(:listname, :tag, :description)
  end
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/views/lists/_count.html.erb
<p>
  <span>
    <% if list.users.count == 1 %>
    <% elsif list.users.count == 2 %>
      avec <%= list.users[0].username%>
    <% else %>
      avec
         <% list.users[0..-2].each do |lu|%>
        <%= lu.username%>,
        <% end %>
    <% end %>
  </span>
</p>

app/views/lists/_edit.html.erb
<%= render partial: "form", locals:{action: "update", method: "put", button_text: "modifier", holder1: "", holder3: "", prefill1: @list.listname, prefill3: @list.description} %>

app/views/lists/_form.html.erb
<%= form_tag url_for(action: action), method: method, class:"p-4", remote: true do %>
  <%= text_field_tag "listname", prefill1, placeholder: holder1, class:"form-control"%>
  <%= select_tag "tag", options_for_select(List::TAG_LIST, @list.tag), class:"form-control"%>
  <%= text_field_tag "description", prefill3, placeholder: holder3, class:"form-control"%>
  <%= submit_tag button_text, class: "btn btn-primary my-2", id:"form_button"%>
<% end %>

app/views/lists/_index.html.erb
  <% lists.sort_by{|l| [l.archived ? 0 : 1, l.updated_at]}.reverse!.each do |l|%>
    <%= render partial:"lists/show", locals: {list: l}%>
  <% end %>

app/views/lists/_new.html.erb
<div class="col-5 m-3 p-3 form new_list_form">
  <%= render partial: "form", locals:{action: "create", method: "post", button_text: "ajouter", holder1: 'Nom de la liste', holder3: 'description, optionnelle' , prefill1: "", prefill2: "", prefill3: ""} %>
</div>

app/views/lists/_show.html.erb
<% if list.archived%>
<div class="col-5 m-3 p-4 form archived_list" id="list<%= list.id %>_form">
<% else %>
<div class="col-5 m-3 p-4 form" id="list<%= list.id %>_form">
<% end %>
  <div class="py-3 px-1" id="list<%= list.id %>_body"><!--list body-->
    <div class="container p-3" id="list<%= list.id%>_head">
      <div class="row my-0 p-3">
        <div class="w-100">
          <p>
            <% if list.archived %>
              <span>[terminée]</span>
            <% end %>
            <strong><%= list.listname%></strong>
          </p>
        </div>
        <p class="small"><%= list.description%></p>
      </div>
      <div class="row pt-2 pb-1 px-3" >
        <div class="col">
          <p><span>catégorie: <%= list.tag%></span></p>
        </div>
        <div class="pb-0 col" id="list<%= list.id%>_button_group col">
          <%= link_to new_list_task_path(list), title:"nouvelle tâche", id: "new_task#{list.id}", remote: true do %>
            <i class="fas fa-plus-circle"></i>
          <% end %>
          <%= link_to edit_list_path(list), title:"modifier détails de la liste", id: "edit_list#{list.id}", method: :get, remote: true do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to list_path(list), title:"supprimer cette liste", id: "delete_list#{list.id}", method: :delete, remote: true do %>
            <i class="far fa-trash-alt pr-1 pl-2"></i>
          <% end %>
          <%= link_to new_list_list_user_path(list), title: "inviter un utilisateur à collaborer", id: "add_link#{list.id}", method: :get, remote: true do %>
            <i class="fas fa-user-plus"></i>
          <% end %>
        </div>
      </div>
      <div class="row px-3" id="list<%= list.id%>_users_count">
        <%= render partial: "lists/count", locals:{list: list}%>
      </div>
      <div id="list<%= list.id%>_edit_zone"><!--meant to be blank-->
      </div>
    </div>
    <div class="pt-3 pb-2" id="list<%= list.id%>_content" >
      <%= render partial:"tasks/show", locals: {list: list}%>
    </div>
  </div><!-- end of list body-->
</div>

app/views/lists/create.js.erb
$(".new_list_form").remove();
$(".new_list_btn").css("display","inline");

$(".all_lists").prepend("<%= escape_javascript(render 'show', list: List.last) %>");

app/views/lists/destroy.js.erb
var list = <%= @list.id%>;
$("#list"+list+"_form").remove();

app/views/lists/edit.js.erb
var list = <%= @list.id%>
$("#list"+list+"_head").css("display","none");
$("#edit_list"+list).css("display","none");
$("#list"+list+"_form").prepend("<%= escape_javascript(render 'edit') %>");

app/views/lists/new.js.erb
$(".new_list_btn").css("display","none");
$(".all_lists").prepend("<%= escape_javascript(render 'lists/new') %>");

app/views/lists/update.js.erb
$(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.lists) %>");