config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: %i[index show destroy] do
    get :show_archived
    get :search
  end

  resources :lists do
    resources :list_users
    resources :tasks
    resources :tasks do
      put :finish
    end
  end
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :list
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  belongs_to :finisher, foreign_key: 'finisher_id', class_name: 'User', optional: true

  validates :title, length: { minimum: 2, message: 'must be longer than 2 chars' }
  validates :title, presence: { message: 'must exist' }
  validate :finished_and_finisher_must_be_present_or_absent_together
  validate :creator_finisher_must_be_among_list_users

  def list_users
    list.users
  end

  def self.recent_creation
    Task.where(created_at: ((Time.now - RECENT_CRITERION)..Time.now))
  end

  def self.recent_finish
    Task.where(created_at: ((Time.now - RECENT_CRITERION)..Time.now)).where(finished: true)
  end

  private

  def finished_and_finisher_must_be_present_or_absent_together
    if finished == true && finisher.nil?
      errors.add(:finisher, 'must exist when task is finished')
    elsif finished == false && !finisher.nil?
      errors.add(:finisher, "mustn't exist when task is unfinished")
    end
  end

  def creator_finisher_must_be_among_list_users
    unless list_users.include? creator
      errors.add(:creator, 'must be among users of this list')
    end
    if !finisher.nil? && !(list_users.include? finisher)
      errors.add(:finisher, 'must be among users of this list')
    end
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :get_current_user
  before_action :get_current_list, only: %i[new create edit update finish destroy]
  before_action :set_task, only: %i[edit update destroy]

  def show; end

  def new
    respond_to do |format|
      @task = Task.new
      format.js {}
    end
  end

  def create
    respond_to do |format|
      @task = Task.create(task_params.merge(list: @list, creator: @user))
      format.js {}
    end
  end

  def edit
    respond_to do |format|
      format.js {}
    end
  end

  def update
    respond_to do |format|
      @task.update(task_params)
      format.js {}
    end
  end

  def finish
    @task = Task.find(params[:task_id])
    @task.update(finished: true, finisher: @user)

    respond_to do |format|
      format.js {}
    end
    send_mail_if_list_archived
  end

  def destroy
    respond_to do |format|
      @task.destroy
      format.js {}
    end
    send_mail_if_list_archived
  end

  private

  def send_mail_if_list_archived
    if @task.list.archived
      congrats_send
    end
  end

  def congrats_send
    UserMailer.congrats(@task.list).deliver_now
  end


  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.permit(:title)
  end

  def get_current_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_tag url_for(action: action), method: method, class:"form_new_edit px-3", remote: true do %>
  <%= text_field_tag "title", prefil, placeholder: holder  ,class:"form-control"%>
  <%= submit_tag button_text, class:"btn btn-primary my-2", id:"form_button"%>
<% end %>

app/views/tasks/_show.html.erb
<% list.tasks.sort_by{|t| t.finished ? 1:0}.each do |t|%>

  <div class="row justify-content-between task" id="task<%=t.id%>">
    <div class="row">
      <div class="col-1"><!--the checkbox-->
        <% if !t.finished%>
          <%= link_to list_task_finish_path(list, t), method: :put, remote: true do %>
            <i class="far fa-check-square"></i>
          <% end %>
        <% end %>
      </div>
      <div class="col-8"><!--the task itself-->
        <div class="container">
          <div class="row">
            <% if t.finished == true %>
              <p class="crossed"><%=t.title %></p>
            <% else %>
              <p><%=t.title %></p>
            <% end %>
          </div>
          <div class="row">
            <% if t.finished == true %>
              <p><span>terminé par <%=t.finisher.username%> le <%= t.updated_at.to_date%></span></p>
            <% else %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-3"><!--the button group-->
        <% if !t.finished%>
          <%= link_to edit_list_task_path(list, t), method: :get, remote: true do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to list_task_path(list, t), method: :delete, remote: true do %>
            <i class="far fa-trash-alt pr-1 pl-2"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/create.js.erb
$(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.lists) %>");

app/views/tasks/destroy.js.erb
$(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.lists) %>");

app/views/tasks/edit.js.erb
task = <%= @task.id%>;
$("#task"+task).html("<%= escape_javascript(render 'form', action: 'update', method: 'put', button_text:'Modifier', holder:'', prefil: Task.find(params[:id]).title) %>");

app/views/tasks/finish.js.erb
$(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.lists) %>");

app/views/tasks/new.js.erb
// line 2 declares var without using keyword "let" nor "var"
// otherwise can't press "new" twice within same page without refreshing
list_id = <%= params[:list_id]%>;
$("#new_task"+list_id).css("display","none");
$("#list"+list_id+"_content").prepend("<%= escape_javascript(render 'tasks/form', action: 'create', method: 'post', button_text:'Ａjouter', prefil: '', holder:'Que souhaitez-vous faire ?') %>");

app/views/tasks/update.js.erb
$(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.lists) %>");