config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: %i[index show destroy] do
    get :show_archived
    get :search
  end

  resources :lists do
    resources :list_users
    resources :tasks
    resources :tasks do
      put :finish
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: { message: 'must exist' }
  validates :username, length: { in: 5..30, message: 'must be between 5-30 chars' }
  validate :user_name_must_start_with_letter

  has_many :list_users
  has_many :lists, through: :list_users
  has_many :tasks_created, foreign_key: 'creator_id', class_name: 'Task'
  has_many :tasks_finished, foreign_key: 'finisher_id', class_name: 'Task'

  def search(n)
    if n
      results = []
      lists.each do |l|
        if l.tasks.where("title LIKE ?", "%#{n}%").count > 0
          results << l
        end
      end
      return results
    else
      return lists
    end
  end

  def self.recent
    User.where(created_at: ((Time.now - RECENT_CRITERION)..Time.now)) # see application record
  end

  private

  def user_name_must_start_with_letter
    # for regex, see Application_record.rb
    if (START_WITH_LETTER_REGEX =~ username).nil?
      errors.add(:username, 'must start with a letter')
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :get_current_user, except:[:destroy] # see application controller
  before_action :check_admin, only: [:index]

  def index
    @users = User.all
  end

  def show
    keyword = params[:search_field]
    @username = @user.username.capitalize
    @nb_list = @user.lists.count
    @ok = @user.lists.map{|l|  l.archived ? 1 : 0}.sum
    @lists = @user.lists
  end

  def search
    respond_to do |format|
      format.js {}
    end
  end

  def show_archived
    respond_to do |format|
      format.js {}
    end
  end


  def destroy
    User.find(params[:id]).destroy
    respond_to do |format|
      format.js {}
    end
  end

  private

  def check_admin
    unless @user.is_admin
      redirect_to root_path
      flash[:notice] = ApplicationController::ACCESS_ERROR_MESSAGE
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_detail.html.erb
<% if user.lists.count == 0 %>
  <p>Cet utilisateur n'a pas encore de liste</p>
<% else %>
  <% user.lists.each do |l| %>
    <div class="col-5 form m-2 p-2">
      <div >
        <p>
        <% if l.archived%>
          <span>[terminée]</span>
        <% end %>
        <strong>(<%= l.id%>)  <%= l.listname%></strong></p>
        <p>
          <span>cat: <%= l.tag%></span>
        </p>
        <p><%= l.description%></p>
      </div>
      <div class="">
        <p>
          <span>
            <% l.users.each do |u|%>
            <%= u.username %>,
            <% end %>
          </span>
        </p>
      </div>
      <div class="">
        <%= render partial:"list_detail", locals:{list: l}%>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/_list_detail.html.erb
<% list.tasks.each do |t| %>
<div class="">
  <p>
    <%= t.title%>
    <% if t.finished %>
      <span>terminé par <%= t.finisher.username%> le <%= t.updated_at.to_date%> </span>
    <% else %>
      <span> en cours</span>
    <% end %>
  </p>
</div>
<% end %>

app/views/users/_user_section.html.erb
  <div class="col-1">
    <p><strong><%=u.id %></strong></p>
  </div>
  <div class="col-1">
    <% if u.is_admin %>
      <i class="fas fa-user-cog" title="administrateur du site"></i>
    <% end %>
  </div>
  <div class="col-3">
    <p><%=u.username %></p>
  </div>
  <div class="col-5">
    <p><%=u.email %></p>
  </div>
  <div class="col-2">
    <%= link_to user_path(u), id: "delete_u#{u.id}", title: "supprimer cet utilisateur", method: :delete, remote: true do %>
      <i class="fas fa-user-times mr-5"></i>
    <% end %>
    <%= link_to user_path(u), id: "goto_u#{u.id}", title: "voir toutes les listes de cet utilisateur", method: :get, remote: true do %>
      <i class="far fa-eye"></i>
    <% end %>

app/views/users/destroy.js.erb
n = "<%= params[:id]%>"
$("#section_u"+n).remove();

app/views/users/index.html.erb
<div class="container py-5">
    <div class="form mb-5 p-5">
      <h2>Dashboard</h2>

    <table>
      <td><i class="fas fa-user-friends"></i><%= User.all.count %></td>
      <td><i class="fas fa-list-ol"></i><%= List.all.count %></td>
      <td><i class="fas fa-thumbtack"></i><%= Task.all.count %></td>
    </table>
    <%= link_to 'retourner au profil', user_path(current_user), class:"btn btn-primary my-2"%>

  </div>

  <div class="form container my-3">
    <div class="row m-3 p-5">
      <div class="col-1 header">
        <h4>Id</h4>
      </div>
      <div class="col-1 header">
      </div>
      <div class="col-3 header">
        <h4>Username</h4>
      </div>
      <div class="col-5 header">
        <h4>Adresse mail</h4>
      </div>
      <div class="col-2 header">
      </div>
    </div>
    <div class="container my-5 pb-5 px-5">
      <% @users.each do |u| %>
        <div class="row user_section my-5 py-1" id="section_u<%=u.id %>">
          <%= render partial: "user_section", locals:{u: u}%>
        </div>
        <div class="row w-100 justify-content-around hidden" id="user_lists<%= u.id %>">
            <%= render partial: "detail", locals:{user: u}%>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/search.js.erb
result = <%= @user.search(params[:search_field]).count%>
if(result === 0){
  alert("Vous n'avez pas de tâche contenant ce mot clé. Veuillez rafraîchier la page pour continuer.");
}
else{
  $(".all_lists").html("<%= escape_javascript(render 'lists/index', lists: @user.search(params[:search_field])) %>");
  $(".archived_list").removeClass("archived_list");
}

app/views/users/show.html.erb
<div class="container centered">
  <div class="row justify-content-between flex-wrap w-100">
    <div class="col-9">
      <div class="container justify-content-center">
        <div class="form py-3 px-5 my-5">
          <div class="row">
            <h2>Bonjour, <%= @username%></h2>
          </div>
          <div class="row">
            <p>Vous avez <%= @user.lists.count%> liste(s), dont <%= @ok%> archivée(s).</p>
          </div>
          <div class="row m-3 p-3">
            <%= form_tag user_search_path(@user), method: :get, class:"form-inline w-100 m-0 p-0", remote: true do %>
              <%= text_field_tag "search_field", "", class:"form-control w-75", placeholder:"Cherchez des tâches par mot clé parmi votre historique"%>
              <%= submit_tag "Chercher", id:"search_button", class: "btn btn-primary mx-2"%>
            <% end %>
          </div>
          <div class="row">
            <div class="col button">
                <%= link_to "Créer une liste", new_list_path, class:"btn btn-primary new_list_btn", remote: true%>
            </div>
            <div class="col button">
                <%= link_to "Voir toutes mes listes", user_show_archived_path(@user), title: "Voir toutes vos listes de tâches, y compris celles qui sont achivées", class:"btn btn-primary", remote: true%>
            </div>
            <% if @user.is_admin%>
              <div class="col button">
                <%= link_to "Admin Board", users_path, class:"btn btn-primary"%>
              </div>
            <% end %>
          </div>

        </div>
      </div>
      <div class="row justify-content-between flex-wrap all_lists">
        <%= render partial: "lists/index", locals:{lists: @lists}%>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.js.erb
id = <%= params[:id]%>
$("#user_lists"+id).removeClass("hidden");

app/views/users/show_archived.js.erb
$(".archived_list").removeClass("archived_list");